//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Information
    {
        public long RegId { get; set; }
        public byte ComID { get; set; }
        public string EmployeeCode { get; set; }
        public string Name { get; set; }
        public string FathersName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Religion { get; set; }
        public string PreAddress { get; set; }
        public string PerAddress { get; set; }
        public string NID { get; set; }
        public string Phone { get; set; }
        public string District { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string Designation { get; set; }
        public string DesigAddi { get; set; }
        public string WStatus { get; set; }
        public bool MLeft { get; set; }
        public bool MLeave { get; set; }
    }
}
