//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_DEMO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EMP_EVALUATIONEntities : DbContext
    {
        public EMP_EVALUATIONEntities()
            : base("name=EMP_EVALUATIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KPI> KPIs { get; set; }
        public virtual DbSet<KRA> KRAs { get; set; }
        public virtual DbSet<STEP> STEPs { get; set; }
        public virtual DbSet<tblMarksEntryHistory> tblMarksEntryHistories { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSpecial_Factor> tblSpecial_Factor { get; set; }
        public virtual DbSet<tblTraining_Need> tblTraining_Need { get; set; }
        public virtual DbSet<tblUser_LogInfo> tblUser_LogInfo { get; set; }
        public virtual DbSet<tblUser_Registration> tblUser_Registration { get; set; }
        public virtual DbSet<tblUserLogHistory> tblUserLogHistories { get; set; }
        public virtual DbSet<Company_Information> Company_Information { get; set; }
        public virtual DbSet<Employee_Information> Employee_Information { get; set; }
        public virtual DbSet<New_Tax_Period> New_Tax_Period { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<View_> View_ { get; set; }
        public virtual DbSet<View_StepDetails> View_StepDetails { get; set; }
    
        [DbFunction("EMP_EVALUATIONEntities", "fnSplitString")]
        public virtual IQueryable<fnSplitString_Result> fnSplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnSplitString_Result>("[EMP_EVALUATIONEntities].[fnSplitString](@string, @delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<prc_GetEmployeeListByDeptHead_Result> prc_GetEmployeeListByDeptHead(Nullable<int> deptHeadValue)
        {
            var deptHeadValueParameter = deptHeadValue.HasValue ?
                new ObjectParameter("DeptHeadValue", deptHeadValue) :
                new ObjectParameter("DeptHeadValue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetEmployeeListByDeptHead_Result>("prc_GetEmployeeListByDeptHead", deptHeadValueParameter);
        }
    
        public virtual ObjectResult<prc_GetKraKpiOutcomeData_Result> prc_GetKraKpiOutcomeData(string employeeCode, Nullable<int> deptHeadValue)
        {
            var employeeCodeParameter = employeeCode != null ?
                new ObjectParameter("EmployeeCode", employeeCode) :
                new ObjectParameter("EmployeeCode", typeof(string));
    
            var deptHeadValueParameter = deptHeadValue.HasValue ?
                new ObjectParameter("DeptHeadValue", deptHeadValue) :
                new ObjectParameter("DeptHeadValue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetKraKpiOutcomeData_Result>("prc_GetKraKpiOutcomeData", employeeCodeParameter, deptHeadValueParameter);
        }
    
        public virtual int prc_UpdateOutcomeMarks(string kpiOutcome, Nullable<int> marksAchieved)
        {
            var kpiOutcomeParameter = kpiOutcome != null ?
                new ObjectParameter("KpiOutcome", kpiOutcome) :
                new ObjectParameter("KpiOutcome", typeof(string));
    
            var marksAchievedParameter = marksAchieved.HasValue ?
                new ObjectParameter("MarksAchieved", marksAchieved) :
                new ObjectParameter("MarksAchieved", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_UpdateOutcomeMarks", kpiOutcomeParameter, marksAchievedParameter);
        }
    
        public virtual ObjectResult<prc_UserMenu_Result> prc_UserMenu(string regId)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_UserMenu_Result>("prc_UserMenu", regIdParameter);
        }
    }
}
