//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser_Registration()
        {
            this.KRAs = new HashSet<KRA>();
        }
    
        public int ID { get; set; }
        public int RegId { get; set; }
        public string Password { get; set; }
        public Nullable<int> DeptHead { get; set; }
        public Nullable<int> ReportSuper { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string BloodGroup { get; set; }
        public string EmailID { get; set; }
        public string EmailID2 { get; set; }
        public string MobileNoPerson { get; set; }
        public string MobileNoHome { get; set; }
        public string PhoneExt { get; set; }
        public string Picture { get; set; }
        public string Role { get; set; }
        public bool Registerd { get; set; }
        public Nullable<int> LoginReq { get; set; }
        public bool YsnActive { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public string last_login_Mac { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRA> KRAs { get; set; }
    }
}
