//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRA
    {
        public int KRA_ID { get; set; }
        public string KRA1 { get; set; }
        public Nullable<int> RegId { get; set; }
        public string Section_Name { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    }
}
