//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEP
    {
        public int ID { get; set; }
        public Nullable<int> SESSION_ID { get; set; }
        public Nullable<int> REG_ID { get; set; }
        public Nullable<int> KRA_ID { get; set; }
        public Nullable<int> KPI_ID { get; set; }
        public string KPI_OUTCOME { get; set; }
        public Nullable<int> Marks_Achieved { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
        public Nullable<bool> YsnUpdate { get; set; }
        public string Remarks { get; set; }
    }
}
