//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_PORTAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using STEP_DEMO.Models;

    public partial class DB_STEPEntities : DbContext
    {
        public DB_STEPEntities()
            : base("name=DB_STEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KPI> KPIs { get; set; }
        public virtual DbSet<KRA> KRAs { get; set; }
        public virtual DbSet<STEP> STEPs { get; set; }
        public virtual DbSet<tbl_StepMaster> tbl_StepMaster { get; set; }
        public virtual DbSet<tblMarksEntryHistory> tblMarksEntryHistories { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSpecial_Factor> tblSpecial_Factor { get; set; }
        public virtual DbSet<tblTraining_Need> tblTraining_Need { get; set; }
        public virtual DbSet<tblUser_LogInfo> tblUser_LogInfo { get; set; }
        public virtual DbSet<tblUserLogHistory> tblUserLogHistories { get; set; }
        public virtual DbSet<Company_Information> Company_Information { get; set; }
        public virtual DbSet<New_Tax_Period> New_Tax_Period { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<View_StepDetails> View_StepDetails { get; set; }
    
        public virtual ObjectResult<prc_EmployeeInfoByEmpCode_Result> prc_EmployeeInfoByEmpCode(Nullable<int> compID, string empCode)
        {
            var compIDParameter = compID.HasValue ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(int));
    
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeInfoByEmpCode_Result>("prc_EmployeeInfoByEmpCode", compIDParameter, empCodeParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeInfoByRegID_Result> prc_EmployeeInfoByRegID(Nullable<int> regID)
        {
            var regIDParameter = regID.HasValue ?
                new ObjectParameter("RegID", regID) :
                new ObjectParameter("RegID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeInfoByRegID_Result>("prc_EmployeeInfoByRegID", regIDParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeInfoByRegIDs_Result> prc_EmployeeInfoByRegIDs(string regID)
        {
            var regIDParameter = regID != null ?
                new ObjectParameter("RegID", regID) :
                new ObjectParameter("RegID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeInfoByRegIDs_Result>("prc_EmployeeInfoByRegIDs", regIDParameter);
        }
    
        public virtual ObjectResult<prc_GetEmployeeListByDeptHead_Result> prc_GetEmployeeListByDeptHead(Nullable<int> deptHeadValue)
        {
            var deptHeadValueParameter = deptHeadValue.HasValue ?
                new ObjectParameter("DeptHeadValue", deptHeadValue) :
                new ObjectParameter("DeptHeadValue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetEmployeeListByDeptHead_Result>("prc_GetEmployeeListByDeptHead", deptHeadValueParameter);
        }
    
        public virtual int prc_GetEmployeesByCompany(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_GetEmployeesByCompany", companyIdParameter);
        }
    
        public virtual ObjectResult<prc_GetKPIOutcomeByRegIdOrSectionName_Result> prc_GetKPIOutcomeByRegIdOrSectionName(Nullable<int> regId, string sectionName)
        {
            var regIdParameter = regId.HasValue ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(int));
    
            var sectionNameParameter = sectionName != null ?
                new ObjectParameter("SectionName", sectionName) :
                new ObjectParameter("SectionName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetKPIOutcomeByRegIdOrSectionName_Result>("prc_GetKPIOutcomeByRegIdOrSectionName", regIdParameter, sectionNameParameter);
        }
    
        public virtual ObjectResult<prc_GetKraKpiByRegIdOrSectionName_Result> prc_GetKraKpiByRegIdOrSectionName(Nullable<int> regId, string sectionName)
        {
            var regIdParameter = regId.HasValue ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(int));
    
            var sectionNameParameter = sectionName != null ?
                new ObjectParameter("SectionName", sectionName) :
                new ObjectParameter("SectionName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetKraKpiByRegIdOrSectionName_Result>("prc_GetKraKpiByRegIdOrSectionName", regIdParameter, sectionNameParameter);
        }
    
        public virtual ObjectResult<prc_GetKraKpiOutcomeData_Result> prc_GetKraKpiOutcomeData(Nullable<int> regId, Nullable<int> sESSION_ID)
        {
            var regIdParameter = regId.HasValue ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(int));
    
            var sESSION_IDParameter = sESSION_ID.HasValue ?
                new ObjectParameter("SESSION_ID", sESSION_ID) :
                new ObjectParameter("SESSION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetKraKpiOutcomeData_Result>("prc_GetKraKpiOutcomeData", regIdParameter, sESSION_IDParameter);
        }
    
        public virtual ObjectResult<prc_GetTeamMember_Result> prc_GetTeamMember(Nullable<int> compID, Nullable<int> regID, Nullable<int> sESSION_ID)
        {
            var compIDParameter = compID.HasValue ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(int));
    
            var regIDParameter = regID.HasValue ?
                new ObjectParameter("RegID", regID) :
                new ObjectParameter("RegID", typeof(int));
    
            var sESSION_IDParameter = sESSION_ID.HasValue ?
                new ObjectParameter("SESSION_ID", sESSION_ID) :
                new ObjectParameter("SESSION_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetTeamMember_Result>("prc_GetTeamMember", compIDParameter, regIDParameter, sESSION_IDParameter);
        }
    
        public virtual int prc_UpdateOutcomeMarks(string kpiOutcome, Nullable<int> marksAchieved)
        {
            var kpiOutcomeParameter = kpiOutcome != null ?
                new ObjectParameter("KpiOutcome", kpiOutcome) :
                new ObjectParameter("KpiOutcome", typeof(string));
    
            var marksAchievedParameter = marksAchieved.HasValue ?
                new ObjectParameter("MarksAchieved", marksAchieved) :
                new ObjectParameter("MarksAchieved", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_UpdateOutcomeMarks", kpiOutcomeParameter, marksAchievedParameter);
        }
    
        public virtual ObjectResult<prc_User_Registration_Result> prc_User_Registration(Nullable<int> regID)
        {
            var regIDParameter = regID.HasValue ?
                new ObjectParameter("RegID", regID) :
                new ObjectParameter("RegID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_User_Registration_Result>("prc_User_Registration", regIDParameter);
        }
    
        public virtual ObjectResult<prc_UserMenu_Result> prc_UserMenu(string regId)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_UserMenu_Result>("prc_UserMenu", regIdParameter);
        }
    }
}
