//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMarksEntryHistory
    {
        public int AutoID { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UserIP { get; set; }
        public string EmployeeID { get; set; }
    }
}
