//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public int NotificationId { get; set; }
        public int EmployeeRegId { get; set; }
        public int SupervisorRegId { get; set; }
        public string NotificationMessage { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
