//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser_LogInfo
    {
        public int RegId { get; set; }
        public System.DateTime login_time { get; set; }
        public string login_Mac { get; set; }
        public Nullable<System.DateTime> logout__time { get; set; }
    }
}
